### ISSUE TITLE
What information is persisted?

### ISSUE THREAD

**Issue by benwilson512** [izelnakri/paper_trail#16]
Hey!

This looks like a valuable library, I really appreciate the commitment to testing and robustness. What information is stored for each version? A snapshot of the changes? or a snapshot of the whole row?

**Comment by izelnakri** [comment]
I've decided to persist only the changes in order to save on overall data size and query speed. The only downside of this approach is reverting back becomes a more expensive operation, one has to fetch all the versions of a single record in order to build up its version state.

Thanks for your compliments, feel free to raise any suggestions / issues you might have in future ;)
