### ISSUE TITLE
Multiple originator models

### ISSUE THREAD

**Issue by zimt28** [izelnakri/paper_trail#26]
Hi,

thank you for this amazing library! In my application, there are multiple types of resources that I manage, `App.TypeA`, `App.TypeB` etc. Some of these resources can have a `App.UserAccount`, where the resource is the actual user. What would be the best way to store the originator? I thought about using the `originator` like `$type:$id`, but actual references would be preferred.

Thank you!

**Comment by izelnakri** [comment]
Thank you for your compliments. Yes you can use an `origin` field like 'user_account:22' or 'remote_account:1' to store additional data about the originator. Originator field intentionally designed to be a foreign-key column to a table/model because this ensures that the data will be consistent. 

Your case seems to be an edge-case, I would create one table that has one-to-one relationship with both models(TypeA and TypeB) and use that table as the originator for versions if I cant merge App.TypeB and App.TypeB tables, this way you get the foreign-key constraint benefit of paper_trail while keeping your models.

**Comment by izelnakri** [comment]
Im closing this issue let me know if you want it to be reopened
